"""Milestone substrate — sequential ordering layer above features.

Per ``project_interviews_milestones_thesis.md``: Interviews capture
operator intent once as requirement artifacts; Milestones organize
those requirements into a multi-run trajectory. tdd-design runs
scoped to a milestone produce features that ship together; the
operator iterates milestone-by-milestone instead of regenerating
the trajectory framing per run.

A Milestone groups requirements into an ordered, named slice with
a definition of done. Status is *derived* from features-that-belong-
to-this-milestone (proposed if nothing queued; in_progress if any
feature is in flight; done if every feature is verified; deferred
if the milestone YAML / markdown says so). No separate lifecycle
log in v1 — the implicit-status approach is the gameplan-approved
shape until it hits a real limit.

Storage at ``<project_root>/.wonderland/milestones/`` mirrors the
other registry patterns but with one key divergence: the registry
*updates by slug*, not append-only. Re-running ``milestone-plan``
after a follow-up discovery should amend the existing plan (extend
a milestone with new requirements, or append a new milestone at
the end) without losing operator-edited content. Same-slug writes
overwrite; new-slug writes append.

Filename shape: ``<NN>-<slug>.md`` where ``NN`` is the milestone's
``order`` (zero-padded). Order is part of the filename so the
sorted directory listing reads as the operator-facing milestone
sequence without an extra index file.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path

from pydantic import BaseModel, Field, model_validator

from wonderland.adr import slugify
from wonderland.interview import Confidence

from wonderland.artifact_guid import new_artifact_guid, short_guid

MILESTONES_DIRNAME = "milestones"


# T-a1 instrumentation: log every milestone file unlink with a stack
# trace so the next M1-deletion repro is debuggable. Mvp-demo lost
# M1 twice via paths the snapshot guard + retract scope guard +
# delete_by_slug audit didn't account for. This wrapper is the
# stitch — any unlink from MilestoneRegistry shows up in
# .wonderland/milestone-unlink.log with full attribution.
def _log_milestone_unlink(
    path: Path, *, reason: str, slug: str, **extras: object,
) -> None:
    """Write an attributed log line whenever a milestone file is
    about to be unlinked. Includes a truncated stack trace so the
    investigator can see who called. Best-effort — never raises."""
    import sys
    import traceback
    from datetime import datetime, timezone

    try:
        project_root = path.parent.parent.parent  # milestones/file.md → project_root
        log_path = project_root / ".wonderland" / "milestone-unlink.log"
        log_path.parent.mkdir(parents=True, exist_ok=True)
        stack = "".join(traceback.format_stack()[-8:-1])  # skip our own frame
        extras_str = " ".join(f"{k}={v!r}" for k, v in extras.items())
        line = (
            f"[{datetime.now(timezone.utc).isoformat()}] "
            f"unlink reason={reason!r} slug={slug!r} path={path.name!r} "
            f"{extras_str}\n"
            f"{stack}\n"
            f"---\n"
        )
        with log_path.open("a", encoding="utf-8") as f:
            f.write(line)
        # Also stderr for live visibility during runs
        sys.stderr.write(
            f"[milestone-unlink] reason={reason!r} slug={slug!r} "
            f"path={path.name!r} {extras_str}\n"
        )
    except Exception:  # noqa: BLE001 — instrumentation must never break the runtime
        pass
_GUID_PATTERN = re.compile(r"^\*\*GUID:\*\*\s*([0-9A-HJKMNP-TV-Z]{26})\s*$", re.MULTILINE)
# T-g3: filename's id-part is either an 8-char ULID prefix (new) or
# a 1-4 digit legacy order number (pre-P18). Order is parsed from
# the markdown header now; the filename's id slot is identity, not
# sequence.
_FILENAME_PATTERN = re.compile(
    r"^milestone-(?P<id>[0-9A-HJKMNP-TV-Z]{8}|\d{1,4})-(?P<slug>[a-z0-9-]+)\.md$"
)
_ORDER_FROM_H2 = re.compile(r"^##\s*Milestone\s+(\d+)\s*:", re.MULTILINE)


class MilestoneKind(StrEnum):
    """T-ab6 — milestone shape classification, parallel to feature.kind.

    Drives substrate behavior at scoping/composition time:

      - ``capability`` (default): user-facing milestone. Stories
        are generated by Alice; features compose user-meaningful
        flows. The classical tdd-design path.
      - ``foundation``: developer/operator-facing plumbing
        (schema, API contracts, seed data, build tooling). Alice
        is filtered out of the scoping phase; Caterpillar
        generates developer-as-user stories solo, avoiding the
        scope-bleed failure mode where Alice invents user
        personas for non-user-facing work and pulls capability-
        milestone scope into the foundation milestone.

    Milestone-plan sets this per milestone; the substrate's
    scoping-phase roster filter reads it.
    """

    CAPABILITY = "capability"
    FOUNDATION = "foundation"


class MilestoneStatus(StrEnum):
    """Lifecycle states a milestone can occupy. v1 derives these
    from features-belonging-to-milestone rather than tracking a
    separate state log — see ``MilestoneRegistry.derive_status`` for
    the derivation logic.

    - ``proposed``: no features have been queued or designed against
      this milestone yet. Default state.
    - ``in_progress``: at least one feature scoped to this
      milestone is in_progress / queued / ready_for_review.
    - ``done``: every feature scoped to this milestone has reached
      a verified terminal state.
    - ``deferred``: milestone is in the plan but explicitly punted
      out of the current cycle (operator-driven; lives in the
      milestone's YAML body).
    """

    PROPOSED = "proposed"
    IN_PROGRESS = "in_progress"
    DONE = "done"
    DEFERRED = "deferred"


class MilestonePayload(BaseModel):
    """Structured payload an agent attaches to a ``milestone``
    utterance during the planning meeting.

    The trio (Rabbit, Cat, Alice) each ships milestones from their
    lens; the substrate writes each via ``MilestoneRegistry.write``,
    which dedups by slug. Same slug = update; new slug = append.
    """

    guid: str = Field(default_factory=new_artifact_guid)
    """P18 — stable Milestone identity. Re-emit with same guid to
    amend (the natural milestone-replan move); coining a new guid
    creates a new milestone. The pre-existing slug field is still
    load-bearing for human readability + back-compat dedup."""

    slug: str = Field(
        min_length=1,
        pattern=r"^[a-z0-9][a-z0-9-]*$",
        description=(
            "Stable identifier — used as the registry key for "
            "update-by-slug semantics. Lowercase letters / digits / "
            "hyphens; no leading hyphen. Pick something short and "
            "meaningful (``foundation``, ``logging-loop``, "
            "``gamification``, ``cloud-mode``); avoid prefixing "
            "with numbers (the order field handles sequencing)."
        ),
    )
    name: str = Field(
        min_length=1,
        description=(
            "Human-readable milestone name (e.g. ``Foundation: "
            "local data layer + profile shell``). Shown in the "
            "dashboard's milestones pane."
        ),
    )
    order: int = Field(
        ge=1,
        description=(
            "1-indexed position in the milestone sequence. Drives "
            "the filename + the dashboard's ordering. Conflicts "
            "(two milestones with the same order) are tolerated — "
            "the registry breaks ties by slug, but agents should "
            "coordinate to keep order unique."
        ),
    )
    goal: str = Field(
        min_length=1,
        description=(
            "One- to three-sentence statement of what this "
            "milestone accomplishes. Becomes part of M1's "
            "convenor_directive when tdd-design runs scoped to "
            "this milestone."
        ),
    )
    done_when: list[str] = Field(
        default_factory=list,
        description=(
            "Observable conditions of done — concrete enough that "
            "the operator (and downstream meetings) can check "
            "them. Each item is one sentence. e.g. 'App launches "
            "on a fresh machine and creates a profile.'"
        ),
    )
    consumes_requirements: list[str] = Field(
        default_factory=list,
        description=(
            "Requirement slugs scoped to this milestone. tdd-design "
            "--milestone <slug> filters M1+ seeds to just these. "
            "Same requirement can belong to multiple milestones if "
            "it's load-bearing for each (e.g., the data-layer "
            "requirement seeds both Foundation and Logging-Loop)."
        ),
    )
    deferred: bool = Field(
        default=False,
        description=(
            "Operator-driven flag marking this milestone as "
            "explicitly deferred. The status derivation reads "
            "this; deferred milestones don't get auto-promoted to "
            "in_progress when features land against them."
        ),
    )
    confidence: Confidence = Field(
        default=Confidence.OPERATOR_STATED,
        description=(
            "Provenance — operator_stated when the operator "
            "approved this milestone, interviewer_inferred when an "
            "agent proposed it without operator confirmation. "
            "Cross-run planning passes can re-confirm by setting "
            "operator_stated."
        ),
    )
    kind: MilestoneKind = Field(
        default=MilestoneKind.CAPABILITY,
        description=(
            "T-ab6 — capability (user-facing) or foundation "
            "(plumbing/contracts/seed-data). Drives scoping-phase "
            "roster: foundation milestones filter Alice out so "
            "Caterpillar generates developer-as-user stories solo, "
            "avoiding the scope-bleed failure mode where Alice "
            "invents user personas for non-user-facing work. "
            "Default capability; milestone-plan sets foundation "
            "when consumes are schema/migration/api-contract/"
            "seed-data shape."
        ),
    )

    @model_validator(mode="after")
    def _consumes_requirements_unique(self) -> "MilestonePayload":
        """Same requirement slug appearing twice in a single
        milestone is almost certainly a bug — fail fast at construct
        time rather than letting M1 see duplicates downstream."""
        seen: set[str] = set()
        dupes: list[str] = []
        for slug in self.consumes_requirements:
            if slug in seen:
                dupes.append(slug)
            seen.add(slug)
        if dupes:
            raise ValueError(
                f"milestone {self.slug!r}: duplicate requirement "
                f"slugs in consumes_requirements: {dupes}"
            )
        return self


@dataclass(frozen=True)
class MilestoneRecord:
    guid: str
    slug: str
    order: int
    name: str
    deferred: bool
    confidence: Confidence
    path: Path
    kind: MilestoneKind = MilestoneKind.CAPABILITY

    def read(self) -> str:
        return self.path.read_text(encoding="utf-8")


def render_milestone(payload: MilestonePayload) -> str:
    """Render a MilestonePayload as the markdown that lands on disk.

    Format mirrors the requirement / ADR / story registries: title
    heading, bold field labels, body sections. ``consumes_requirements``
    renders as a bulleted list; ``done_when`` ditto.
    """
    lines: list[str] = [
        f"## Milestone {payload.order:02d}: {payload.name}",
        "",
        f"**GUID:** {payload.guid}",
        f"**Slug:** {payload.slug}",
        f"**Order:** {payload.order}",
        f"**Kind:** {payload.kind.value}",
        f"**Deferred:** {'true' if payload.deferred else 'false'}",
        f"**Confidence:** {payload.confidence.value}",
        "",
        "**Goal:**",
        "",
        payload.goal.rstrip(),
        "",
    ]
    if payload.done_when:
        lines.extend(
            [
                "**Done when:**",
                "",
            ]
        )
        lines.extend(f"- {item}" for item in payload.done_when)
        lines.append("")
    if payload.consumes_requirements:
        lines.extend(
            [
                "**Consumes requirements:**",
                "",
            ]
        )
        lines.extend(
            f"- {slug}" for slug in payload.consumes_requirements
        )
        lines.append("")
    return "\n".join(lines)


class MilestoneRegistry:
    """Read/write registry over ``<project_root>/.wonderland/milestones/``.

    Key divergence from the other registries: **updates by slug, not
    append-only**. Re-running ``milestone-plan`` after a follow-up
    discovery should amend the existing plan without duplicating
    milestones — same slug means overwrite the file in place.

    Filename: ``milestone-NN-slug.md`` where NN is the order
    (zero-padded). Order can change between writes; the registry
    renames the file when ``order`` shifts so the sorted directory
    listing stays consistent with the operator-facing sequence.
    """

    def __init__(self, project_root: Path) -> None:
        self._root = project_root / ".wonderland" / MILESTONES_DIRNAME

    @property
    def path(self) -> Path:
        return self._root

    # ------------------------------------------------------------------ #
    # Queries
    # ------------------------------------------------------------------ #

    def list_milestones(self) -> list[MilestoneRecord]:
        """All milestones on disk, sorted by order then slug. Order
        is the operator-facing sequence; slug breaks ties (rare —
        agents should coordinate to keep order unique)."""
        if not self._root.is_dir():
            return []
        records: list[MilestoneRecord] = []
        for entry in self._root.iterdir():
            if not entry.is_file():
                continue
            record = self._record_from_path(entry)
            if record is not None:
                records.append(record)
        records.sort(key=lambda r: (r.order, r.slug))
        return records

    def find_by_guid(self, guid: str) -> MilestoneRecord | None:
        """P18 T-g2 — primary identity lookup."""
        if not guid:
            return None
        for record in self.list_milestones():
            if record.guid == guid:
                return record
        return None

    def find_by_slug(self, slug: str) -> MilestoneRecord | None:
        for record in self.list_milestones():
            if record.slug == slug:
                return record
        return None

    def find_by_order(self, order: int) -> MilestoneRecord | None:
        for record in self.list_milestones():
            if record.order == order:
                return record
        return None

    def next_order(self) -> int:
        """Smallest unused order number. Used by agents to append a
        new milestone at the end without colliding with existing
        ones; new plans typically start fresh from 1."""
        existing = self.list_milestones()
        if not existing:
            return 1
        return max(r.order for r in existing) + 1

    # ------------------------------------------------------------------ #
    # Writes (update-by-slug)
    # ------------------------------------------------------------------ #

    def write(
        self, payload: MilestonePayload | dict
    ) -> MilestoneRecord:
        """Create or update a milestone by slug. Existing milestone
        with the same slug → overwrite (filename may change if
        ``order`` shifted). New slug → append."""
        validated = (
            payload
            if isinstance(payload, MilestonePayload)
            else MilestonePayload.model_validate(payload)
        )

        # T-ab14 + T-ab65 — kind-consistency check. Catches the
        # failure modes the milestone-plan directive (T-ab13)
        # doesn't reliably prevent on its own:
        #   1. kind=foundation with user-facing success_criterion in
        #      consumes — directive said don't do this; agents
        #      sometimes still do. RAISES.
        #   2. kind=capability when consumes are all foundation-
        #      appropriate (no success_criterion, no behavior) AND
        #      name signals foundation — observed in mvp-demo-rerun
        #      where M1 "Persistence and API foundation" was tagged
        #      capability, breaking T-ab6's roster filter downstream.
        #      RAISES.
        #   3. T-ab65: kind=capability when title starts with
        #      "Foundation:" OR slug contains "foundation" —
        #      LDR-rerun pilot showed checks 1+2 miss the case
        #      where the agent cites at least one capability-axis
        #      requirement alongside the foundation-axis ones,
        #      satisfying check 2's escape. AUTOPROMOTES (silently
        #      sets kind=foundation + logs) rather than rejects:
        #      v2 of LDR-rerun showed agents adapt around reject-mode
        #      by changing titles to avoid the trigger, while the
        #      milestone shape stays foundation. Autopromote
        #      ratifies the agent's literal-word signal into the
        #      right kind tag, avoiding retry-cost.
        # Checks 1+2 raise; check 3 returns the (possibly-promoted)
        # payload. Caller must use the returned value to persist.
        validated = self._validate_kind_consistency(validated)

        # T-g2: guid-first lookup; slug fallback for back-compat
        # (milestones predate guid; existing milestones on disk match
        # by slug). On a guid hit the slug can drift — the payload's
        # slug wins, the on-disk file is renamed.
        existing = self.find_by_guid(validated.guid)
        if existing is None:
            existing = self.find_by_slug(validated.slug)

        if existing is not None and existing.guid:
            validated = validated.model_copy(update={"guid": existing.guid})

        # T-g3: filename embeds short_guid for substrate identity.
        # Order moves into the H2 header — reordering no longer
        # requires file rename. Slug rename still triggers file
        # rename (slug is part of the filename for browsability).
        new_path = self._path_for_guid(validated.guid, validated.slug)
        if existing is not None and existing.path.is_file():
            if existing.path != new_path:
                _log_milestone_unlink(
                    existing.path,
                    reason="write_rename",
                    slug=existing.slug,
                    new_path=str(new_path),
                )
                try:
                    existing.path.unlink()
                except OSError:
                    pass
        target = new_path

        self._root.mkdir(parents=True, exist_ok=True)
        target.write_text(
            render_milestone(validated), encoding="utf-8"
        )

        return MilestoneRecord(
            guid=validated.guid,
            slug=validated.slug,
            order=validated.order,
            name=validated.name,
            deferred=validated.deferred,
            confidence=validated.confidence,
            path=target,
            kind=validated.kind,
        )

    def delete_by_slug(self, slug: str) -> bool:
        """Remove a milestone file. Returns True if found and
        deleted, False otherwise. Used by operator pruning + by
        the planning loop when an agent proposes consolidating
        two milestones into one."""
        record = self.find_by_slug(slug)
        if record is None:
            return False
        _log_milestone_unlink(record.path, reason="delete_by_slug", slug=slug)
        try:
            record.path.unlink()
        except OSError:
            return False
        return True

    # ------------------------------------------------------------------ #
    # Derived status
    # ------------------------------------------------------------------ #

    @staticmethod
    def derive_status(
        *,
        deferred: bool,
        feature_states: list[str],
    ) -> MilestoneStatus:
        """Roll feature states up to a milestone status.

        Inputs: the milestone's ``deferred`` flag + the lifecycle
        states of the features that consume this milestone's
        requirements (resolved by the dashboard via
        ``MilestoneRegistry.features_for``).

        Rules:
          - deferred → DEFERRED (operator-driven; status doesn't
            move regardless of feature state)
          - no features → PROPOSED (nothing's been designed yet)
          - any feature is verified-or-better AND not all features
            are verified → IN_PROGRESS (at least one feature in
            flight, work isn't complete)
          - any feature is queued / in_progress / ready_for_review
            / designed → IN_PROGRESS
          - all features are verified → DONE
          - otherwise (e.g., all features are still proposed) →
            PROPOSED
        """
        if deferred:
            return MilestoneStatus.DEFERRED
        if not feature_states:
            return MilestoneStatus.PROPOSED

        all_verified = all(s == "verified" for s in feature_states)
        if all_verified:
            return MilestoneStatus.DONE

        any_in_flight = any(
            s
            in (
                "designed",
                "queued",
                "in_progress",
                "ready_for_review",
                "verified",
            )
            for s in feature_states
        )
        if any_in_flight:
            return MilestoneStatus.IN_PROGRESS

        return MilestoneStatus.PROPOSED

    # ------------------------------------------------------------------ #
    # Internals
    # ------------------------------------------------------------------ #

    def _validate_kind_consistency(
        self, payload: MilestonePayload
    ) -> MilestonePayload:
        """T-ab14 + T-ab15 — enforce milestone.kind ↔ consumes-axis
        coherence.

        Reads each consumed requirement's ``**Axis:**`` field (T-ab15)
        and checks two failure modes:

        1. ``kind=foundation`` consuming a ``capability``-axis
           requirement: foundation milestones don't deliver
           user-facing behavior; that requirement belongs to a
           capability milestone.

        2. ``kind=capability`` consuming only ``foundation``-axis
           requirements (no capability- or both-axis): milestone is
           doing foundation work but tagged capability, which
           silently disables T-ab6's roster filter (Cat-solo on
           foundation scoping). Observed in mvp-demo-rerun: M1
           "Persistence and API foundation" tagged capability →
           Alice was in scoping → capability stories flooded the
           foundation milestone.

        ``both``-axis requirements are permissive — they apply
        across both contexts (persona requirements, cross-cutting
        scope) so they don't trigger either check.

        Legacy requirements (pre-T-ab15, no ``**Axis:**`` line)
        default to ``both``, making the validator quiet on
        pre-axis projects until they migrate. New projects' axis
        classification is captured at discovery time.

        Best-effort: if requirement files can't be read or no
        recognizable axis is set, skip the check rather than
        blocking writes.
        """
        from wonderland.coverage import _parse_requirement_axis

        # T-ab65 autopromote helper — applied at every early-return
        # so the caller always receives a (possibly-mutated) payload.
        def _maybe_autopromote(p: MilestonePayload) -> MilestonePayload:
            if p.kind != MilestoneKind.CAPABILITY:
                return p
            title_signals = re.match(
                r"^foundation:", p.name.strip(), re.IGNORECASE
            )
            slug_signals = "foundation" in p.slug.lower()
            if not (title_signals or slug_signals):
                return p
            reason = "title-prefix" if title_signals else "slug"
            sys.stderr.write(
                f"[milestone-autopromote] slug={p.slug!r} "
                f"kind: capability → foundation "
                f"(signal: foundation in {reason})\n"
            )
            return p.model_copy(update={"kind": MilestoneKind.FOUNDATION})

        req_root = self._root.parent / "requirements"
        if not req_root.is_dir():
            return _maybe_autopromote(payload)
        req_axes: dict[str, str] = {}
        filename_re = re.compile(
            r"requirement-(?:[0-9A-HJKMNP-TV-Z]{8}|\d{1,4})-(.+)\.md"
        )
        for path in req_root.glob("requirement-*.md"):
            m = filename_re.match(path.name)
            if not m:
                continue
            try:
                text = path.read_text(encoding="utf-8")
            except OSError:
                continue
            axis = _parse_requirement_axis(text)
            # Default to "both" for legacy requirements without axis line
            req_axes[m.group(1)] = axis if axis is not None else "both"

        consumed_axes: list[tuple[str, str]] = []
        for slug_cite in payload.consumes_requirements:
            slug = (
                slug_cite.split(":", 1)[1]
                if ":" in slug_cite
                else slug_cite
            )
            axis = req_axes.get(slug)
            if axis is not None:
                consumed_axes.append((slug, axis))

        if not consumed_axes:
            return _maybe_autopromote(payload)

        # Check 1: foundation milestone consuming capability-axis.
        if payload.kind == MilestoneKind.FOUNDATION:
            offenders = [
                (s, a) for s, a in consumed_axes if a == "capability"
            ]
            if offenders:
                offender_list = ", ".join(
                    f"{s!r}" for s, _ in offenders[:3]
                )
                if len(offenders) > 3:
                    offender_list += f", + {len(offenders)-3} more"
                raise ValueError(
                    f"milestone {payload.slug!r} is tagged "
                    f"``kind: foundation`` but consumes "
                    f"capability-axis requirement(s): "
                    f"{offender_list}. Foundation milestones stub "
                    f"endpoints / set up infrastructure; user-visible "
                    f"behavior belongs to the capability milestone "
                    f"that delivers it. Move the listed "
                    f"requirement(s) to the capability milestone's "
                    f"consumes_requirements."
                )

        # Check 2: capability milestone with all foundation-axis
        # consumes (no capability- or both-axis). The "should be
        # foundation" case.
        if payload.kind == MilestoneKind.CAPABILITY:
            has_non_foundation_axis = any(
                a != "foundation" for _, a in consumed_axes
            )
            if not has_non_foundation_axis:
                raise ValueError(
                    f"milestone {payload.slug!r} is tagged "
                    f"``kind: capability`` but every consumed "
                    f"requirement has axis ``foundation``. This is "
                    f"infrastructure work — the substrate's "
                    f"foundation-mode roster filter "
                    f"(Caterpillar-solo on foundation scoping) "
                    f"won't fire for a capability-tagged milestone, "
                    f"and Alice will produce user-facing stories "
                    f"for what's actually plumbing. Re-emit this "
                    f"milestone with ``kind: foundation``, OR add "
                    f"capability-axis requirement(s) that justify "
                    f"capability framing."
                )

        # T-ab65 Check 3: autopromote on foundation-signal in title
        # or slug. Originally implemented as reject-and-retry but
        # LDR-rerun v2 showed agents adapt around reject-mode by
        # moving "Foundation" out of the title-prefix position
        # (renamed to "Auth + Session Foundation" while slug stayed
        # m1-auth-session-foundation and kind stayed capability).
        # Autopromote is more aligned with the substrate's "state
        # is primary; agents propose, substrate ratifies" principle:
        # the literal word "Foundation:" in the title prefix OR
        # "foundation" in the slug IS the agent's intent signal;
        # substrate translates that signal into the right kind tag
        # rather than forcing the agent to learn the routing-meta-
        # language.
        #
        # Trigger: title starts with "Foundation:" (case-insensitive,
        # colon-anchored — natural English doesn't use "Foundation:"
        # as a prefix outside the routing convention, so essentially
        # zero false positives) OR slug contains "foundation"
        # (agent-chosen tokens; "foundation" in a slug is always the
        # routing keyword, not metaphor). Autopromote happens at
        # every early-return via _maybe_autopromote — this final
        # call is for the path where checks 1+2 ran cleanly.
        return _maybe_autopromote(payload)

    def _path_for(self, order: int, slug: str) -> Path:
        """Legacy filename — kept for back-compat with pre-T-g3 callers.
        New writes go through ``_path_for_guid``."""
        return self._root / f"milestone-{order:02d}-{slug}.md"

    def _path_for_guid(self, guid: str, slug: str) -> Path:
        """T-g3 filename: short_guid embedded for substrate identity."""
        return self._root / f"milestone-{short_guid(guid)}-{slug}.md"

    @staticmethod
    def _record_from_path(path: Path) -> MilestoneRecord | None:
        match = _FILENAME_PATTERN.match(path.name)
        if not match:
            return None
        id_part = match.group("id")
        slug = match.group("slug")
        name, deferred, confidence, kind = (
            MilestoneRegistry._fields_from_file(
                path, fallback_name=slug
            )
        )
        guid = MilestoneRegistry._guid_from_file(path)
        order = MilestoneRegistry._order_from_file(path, id_part)
        return MilestoneRecord(
            guid=guid,
            slug=slug,
            order=order,
            name=name,
            deferred=deferred,
            confidence=confidence,
            path=path,
            kind=kind,
        )

    @staticmethod
    def _order_from_file(path: Path, id_part: str) -> int:
        """T-g3 — legacy milestone filenames carried order in the id
        slot (zero-padded 2-digit). New-shape files keep order only
        in the H2 header. Filename's id slot is identity, not order."""
        if id_part.isdigit():
            return int(id_part)
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            return 0
        m = _ORDER_FROM_H2.search(text)
        return int(m.group(1)) if m else 0

    @staticmethod
    def _guid_from_file(path: Path) -> str:
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            return new_artifact_guid()
        m = _GUID_PATTERN.search(text)
        return m.group(1) if m else new_artifact_guid()

    @staticmethod
    def _fields_from_file(
        path: Path, *, fallback_name: str
    ) -> tuple[str, bool, Confidence, MilestoneKind]:
        """Parse the first several lines for name + deferred +
        confidence + kind. Tolerates operator hand-edits — same shape
        as the requirement registry's parser."""
        name = fallback_name
        deferred = False
        confidence = Confidence.OPERATOR_STATED
        kind = MilestoneKind.CAPABILITY
        try:
            with path.open(encoding="utf-8") as f:
                lines = [f.readline() for _ in range(10)]
        except OSError:
            return name, deferred, confidence, kind
        for line in lines:
            stripped = line.strip()
            if stripped.startswith("## Milestone"):
                if ":" in stripped:
                    name = stripped.split(":", 1)[1].strip() or name
            elif stripped.startswith("**Deferred:**"):
                raw = stripped.removeprefix("**Deferred:**").strip().lower()
                deferred = raw == "true"
            elif stripped.startswith("**Confidence:**"):
                raw = stripped.removeprefix("**Confidence:**").strip()
                try:
                    confidence = Confidence(raw)
                except ValueError:
                    pass
            elif stripped.startswith("**Kind:**"):
                raw = stripped.removeprefix("**Kind:**").strip().lower()
                try:
                    kind = MilestoneKind(raw)
                except ValueError:
                    pass
        return name, deferred, confidence, kind


__all__ = [
    "MILESTONES_DIRNAME",
    "Milestone",
    "MilestoneKind",
    "MilestonePayload",
    "MilestoneRecord",
    "MilestoneRegistry",
    "MilestoneStatus",
    "render_milestone",
]


# Backwards-friendly alias so code importing ``Milestone`` from the
# top-level wonderland namespace finds the payload model directly
# (mirrors how ``Story`` / ``Ticket`` are exposed without a
# ``-Payload`` suffix in many call sites).
Milestone = MilestonePayload
